export const AUTH = "AUTH";
export const VERIFY_AUTH = "VERIFY_AUTH";
export const LOGOUT = "LOGOUT";
export const UPDATE_PROFILE = "UPDATE_PROFILE";
export const AUTH_ERROR = "AUTH_ERROR";
export const ADD_NOTIFICATION_MSG = "ADD_NOTIFICATION_MSG";
export const REMOVE_NOTIFICATION_MSG = "REMOVE_NOTIFICATION_MSG";
